name: Deploy node app to productiond

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t tamiraa468/ti_back:latest .

      - name: Push Docker image to DockerHub
        run: docker push tamiraa468/ti_back:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: docker pull tamiraa468/ti_back:latest

      - name: Stop existing container
        run: docker stop ti_back || true

      - name: Remove existing container
        run: docker rm ti_back || true

      - name: Run new container
        run: docker run -d -p 8000:8000 --name ti_back -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} tamiraa468/ti_back:latest
